/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.palmaactiva.javaformacion.ui;

import com.palmaactiva.javaformacion.io.ProveedorDatos;
import com.palmaactiva.javaformacion.lib.Alumno;
import com.palmaactiva.javaformacion.lib.Curso;
import com.palmaactiva.javaformacion.lib.Persona;
import com.palmaactiva.javaformacion.lib.Profesor;
import com.palmaactiva.javaformacion.ui.validacion.ValidadorNuevaPersona;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Fran Grau <fran@kydemy.com>
 */
public class DialogoNuevaPersona extends javax.swing.JDialog {

    private java.lang.Class<? extends Persona> tipoPersona;
    private VentanaPrincipal ventanaPrincipal;
    private InputVerifier validadorFormulario;
    private Curso[] cursos;
    private Persona personaAEditar;

    /**
     * Creates new form DialogoNuevoAlumno
     */
    public <T extends Persona> DialogoNuevaPersona(java.awt.Frame parent, boolean modal, java.lang.Class<T> tipoPersona, ProveedorDatos datos) {
        super(parent, modal);
        initComponents();
        this.tipoPersona = tipoPersona;
        this.ventanaPrincipal = (VentanaPrincipal) parent;
        this.validadorFormulario = new ValidadorNuevaPersona();
        DefaultListModel modeloListaCursos = new DefaultListModel();
        Collection<Curso> todosLosCursos = datos.getCursos();
        this.cursos = todosLosCursos.toArray(new Curso[todosLosCursos.size()]);
        Arrays.sort(this.cursos);
        modeloListaCursos.addAll(Arrays.asList(cursos));
        this.ListaClases.setModel(modeloListaCursos);

        if (tipoPersona == Profesor.class) {
            DefaultListModel modeloListaCategorias = new DefaultListModel();
            Curso.CategoríaCurso[] categorias = Curso.CategoríaCurso.values();
            Arrays.sort(categorias);
            modeloListaCategorias.addAll(Arrays.asList(categorias));
            this.ListaCategorias.setModel(modeloListaCategorias);
            this.PanelCategorias.setVisible(true);
        } else {
            this.PanelCategorias.setVisible(false);
        }
        this.pack();
    }

    public DialogoNuevaPersona(java.awt.Frame parent, boolean modal, Persona personaAEditar, ProveedorDatos datos) {
        this(parent, modal, personaAEditar.getClass(), datos);
        this.CampoNombre.setText(personaAEditar.getNombre());
        this.CampoApellidos.setText(personaAEditar.getApellidos());
        this.personaAEditar = personaAEditar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDNINIE = new javax.swing.ButtonGroup();
        EtiquetaNombre = new javax.swing.JLabel();
        EtiquetaApellidos = new javax.swing.JLabel();
        PanelDNI = new javax.swing.JPanel();
        RadioDNI = new javax.swing.JRadioButton();
        RadioNIE = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        CampoNumeroDNI = new javax.swing.JFormattedTextField();
        ComboLetraNIE = new javax.swing.JComboBox<>();
        EtiquetaFechaNacimiento = new javax.swing.JLabel();
        CampoFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        ButtonCancelar = new javax.swing.JButton();
        ButtonCrear = new javax.swing.JButton();
        CampoNombre = new javax.swing.JTextField();
        CampoApellidos = new javax.swing.JTextField();
        PanelCategorias = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaCategorias = new javax.swing.JList<>();
        PanelCursos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaClases = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nueva Persona");

        EtiquetaNombre.setText("Nombre:");
        EtiquetaNombre.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        EtiquetaApellidos.setText("Apellidos:");
        EtiquetaApellidos.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        PanelDNI.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI / NIE"));

        GrupoDNINIE.add(RadioDNI);
        RadioDNI.setSelected(true);
        RadioDNI.setText("DNI");
        RadioDNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioDNIStateChanged(evt);
            }
        });

        GrupoDNINIE.add(RadioNIE);
        RadioNIE.setText("NIE");

        jLabel3.setText("Número:");
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        CampoNumeroDNI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        CampoNumeroDNI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CampoNumeroDNI.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        CampoNumeroDNI.setInputVerifier(getValidadorFormularion());

        ComboLetraNIE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "X", "Y", "Z" }));
        ComboLetraNIE.setEnabled(false);
        ComboLetraNIE.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout PanelDNILayout = new javax.swing.GroupLayout(PanelDNI);
        PanelDNI.setLayout(PanelDNILayout);
        PanelDNILayout.setHorizontalGroup(
            PanelDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDNILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDNILayout.createSequentialGroup()
                        .addComponent(RadioDNI)
                        .addGap(18, 18, 18)
                        .addComponent(RadioNIE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelDNILayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboLetraNIE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelDNILayout.setVerticalGroup(
            PanelDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDNILayout.createSequentialGroup()
                .addGroup(PanelDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioDNI)
                    .addComponent(RadioNIE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboLetraNIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        EtiquetaFechaNacimiento.setText("Fecha Nacimiento:");
        EtiquetaFechaNacimiento.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        CampoFechaNacimiento.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonCrear.setText("CREAR");
        ButtonCrear.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        ButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearActionPerformed(evt);
            }
        });

        CampoNombre.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        CampoNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CampoNombre.setInputVerifier(getValidadorFormularion());

        CampoApellidos.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        CampoApellidos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CampoApellidos.setInputVerifier(getValidadorFormularion());

        PanelCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder("Categorías"));
        PanelCategorias.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setViewportView(ListaCategorias);

        PanelCategorias.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        PanelCursos.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos"));
        PanelCursos.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(ListaClases);

        PanelCursos.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(EtiquetaFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CampoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(ButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(EtiquetaApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(EtiquetaNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaNombre)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaApellidos)
                    .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaFechaNacimiento)
                    .addComponent(CampoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(ButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void RadioDNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioDNIStateChanged
        if (RadioDNI.isSelected()) {
            this.ComboLetraNIE.setSelectedIndex(0);
            this.ComboLetraNIE.setEnabled(false);
        } else {
            this.ComboLetraNIE.setSelectedIndex(1);
            this.ComboLetraNIE.setEnabled(true);
        }
    }//GEN-LAST:event_RadioDNIStateChanged

    private void ButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearActionPerformed
        try {
            if (this.personaAEditar == null) {
                this.crearNuevaPersona();
            } else {
                this.guardarPersona();
            }
            this.ventanaPrincipal.actualizarDatos();
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos y asegurate que los formatos son correctos.", "Error creando entidad", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonCrearActionPerformed

    private void crearNuevaPersona() {
        Persona nuevaPersona = null;
        if (this.tipoPersona == Alumno.class) {
            nuevaPersona = this.crearAlumno();
        } else {
            nuevaPersona = this.crearProfesor();
        }
        this.ventanaPrincipal.añadirTabulable(nuevaPersona);
    }

    private void guardarPersona() {
        // TODO Setters
    }

    protected InputVerifier getValidadorFormularion() {
        return this.validadorFormulario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonCrear;
    private javax.swing.JTextField CampoApellidos;
    private com.github.lgooddatepicker.components.DatePicker CampoFechaNacimiento;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JFormattedTextField CampoNumeroDNI;
    private javax.swing.JComboBox<String> ComboLetraNIE;
    private javax.swing.JLabel EtiquetaApellidos;
    private javax.swing.JLabel EtiquetaFechaNacimiento;
    private javax.swing.JLabel EtiquetaNombre;
    private javax.swing.ButtonGroup GrupoDNINIE;
    private javax.swing.JList<String> ListaCategorias;
    private javax.swing.JList<String> ListaClases;
    private javax.swing.JPanel PanelCategorias;
    private javax.swing.JPanel PanelCursos;
    private javax.swing.JPanel PanelDNI;
    private javax.swing.JRadioButton RadioDNI;
    private javax.swing.JRadioButton RadioNIE;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private Persona crearPersona() {
        String nombre = this.CampoNombre.getText().trim();
        String apellidos = this.CampoApellidos.getText().trim();
        int numeroDNI = Integer.parseInt(this.CampoNumeroDNI.getText());
        Date fechaNacimiento = Date.from(this.CampoFechaNacimiento.getDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
        return new Persona(nombre, apellidos, fechaNacimiento, numeroDNI);
    }

    private Alumno crearAlumno() {
        Alumno alumno = new Alumno(this.crearPersona());
        int[] clasesSeleccionadas = this.ListaClases.getSelectedIndices();
        for (int indiceCurso : clasesSeleccionadas) {
            this.cursos[indiceCurso].addAlumno((Alumno) alumno);
        }

        return alumno;
    }

    private Profesor crearProfesor() {
        Profesor profe = new Profesor(this.crearPersona());
        int[] clasesSeleccionadas = this.ListaClases.getSelectedIndices();
        for (int indiceCurso : clasesSeleccionadas) {
            this.cursos[indiceCurso].setDocente((Profesor) profe);
        }

        return profe;
    }
}
